export const socialIconData = [
  {
    id: 1,
    icon: "fab fa-facebook",
    name: "Facebook",
    className: "primary-outlined",
    isTrue: true,
    sourceLink:
      "https://www.facebook.com/iftekhar.hussain.969300?mibextid=ZbWKwL",
  },
  {
    id: 2,
    icon: "fab fa-twitter",
    name: "Twitter",
    isTrue: true,
    className: "primary-outlined",
    sourceLink: "https://x.com/IftekharAhmd?t=gsqw9q2d-3n-mRZx3e-unA&s=09",
  },
  {
    id: 3,
    icon: "fab fa-instagram",
    name: "Instagram",
    isTrue: true,
    className: "warning-outlined",
    sourceLink:
      "https://www.instagram.com/iftekharal7?igsh=MWZ5NTF1MXF0anVhcQ==",
  },
  {
    id: 4,
    icon: "fab fa-linkedin-in",
    isTrue: true,
    name: "Linkedin",
    className: "primary-outlined",
    sourceLink: "https://www.linkedin.com/in/mohammad-iftekhar-8a3261194",
  },
  {
    id: 5,
    icon: "fab fa-github",
    name: "Github",
    className: "ghost-outlined",
    sourceLink: "https://github.com/iftekhar7",
  },
  {
    id: 6,
    icon: "fab fa-whatsapp",
    name: "WhatsApp",
    className: "primary-outlined",
    sourceLink: "https://wa.me/917626883755",
  },
  {
    id: 7,
    icon: "fas fa-envelope",
    name: "Email",
    className: "success-outlined",
    sourceLink: "mailto:iftekharhussain120@gmail.com",
  },
];

export const cardData = [
  {
    id: 1,
    projectName: "Flex83 - AIoT Platform - version 7",
    companyName: "@iot83",
    description:
      "The Flex83 AIoT Platform serves as a unified interface that connects, manages, and monitors all core components across your data and analytics ecosystem.",
    url: "https://res.cloudinary.com/dhvkeskni/image/upload/v1766334685/Screenshot_2025-12-21_220019_mzentr.png",
    languages: [ 
      "React",
      "TypeScript",
      'Redux',
      'RTK Query',
      "HTML5",
      "CSS",
      "Scss",
      "ApacheEchart", 
    ],  
    designStatus: "Dashboard",
    startDate: "Dec 2024",
    endDate: "May 2025",
  },
  {
    id: 1,
    projectName: "MAH (Multi Asset Handler) - Version 6 ",
    companyName: "@iot83",
    description:
      "Built an IoT device management system that enables seamless device lifecycle management and firmware updates for large-scale IoT deployments",
    url: "https://res.cloudinary.com/dhvkeskni/image/upload/v1766330998/Screenshot_2025-12-21_205849_kcmqro.png",
    languages: [
      "React",
      "TypeScript",
       'Redux',
      'RTK Query',
      "HTML5",
      "CSS",
      "Scss",
      "AmCharts",
    ], 
    designStatus: "Dashboard",
    startDate: "Dec 2024",
    endDate: "May 2025",
  },
  {
    id: 4,
    projectName: "OEDC (Data Studio Application) ",
    companyName: "@iot83",
    startDate: "Nov 2023",
    endDate: "Dec 2024",
    description:
      "Built a dynamic data visualization platform with custom dashboards tailored to user needs",
    url: "https://res.cloudinary.com/dhvkeskni/image/upload/v1766330645/oedc-login_qhgm6k.png",
    languages: [
      "React",
      "JavaScript",
       'Redux',
      'RTK Query',
      "HTML5",
      "CSS",
      "Scss",
      "AmCharts",
    ], 
    designStatus: "Dashboard",
  },
  {
    id: 5,
    projectName: "SGRM (Smart Generator Remote Monitoring) ",
    companyName: "@iot83",
    description:
      "Built an IoT device management platform to monitor generator status in real time, helping teams perform timely maintenance and reduce downtime.",
    languages: [
      "React",
      "JavaScript",
       'Redux',
      'RTK Query',
      "HTML5",
      "BootStrap",
      "Scss",
      "AmCharts",
    ],
    url:'https://res.cloudinary.com/dhvkeskni/image/upload/v1766334370/sgrm-login_jopghe.png',
    
    designStatus: "Dashboard",
  },
  {
    id: 1,
    projectName: "IAP – Integrated Automation Platform (SIEMENS)",
    companyName: "@iot83",
    description:
      "Create a unified platform that integrates diverse facility management systems into a single scalable web application",
    image: "/siemens/seimens1.png",
    languages: [
      "React",
      "JavaScript",
       'Redux', 
      "HTML5",
      "BootStrap",
      "Scss",
      "AmCharts",
    ],
    url:'https://res.cloudinary.com/dhvkeskni/image/upload/v1766329535/seimens4_i9joeo.png',
    
    designStatus: "Dashboard",
     startDate: "Nov 2022",
    endDate: "Dec 2023",
  },
  {
    id: 7,
    projectName: "Eaton",
    companyName: "@iot83",
    url: "https://res.cloudinary.com/dhvkeskni/image/upload/v1766331792/dlm-login_no6oyc.png",
    description: "Stakeholder and governance risk management system",
    languages: ["React", "TypeScript", "HTML5", "MUI", "Scss", "AmCharts"],
     
    designStatus: "Dashboard",
  },

  {
    id: 6,
    projectName: "Shorting Hat (True Feature)",
    companyName: "@iot83",
    description:
      "Interactive dashboard with real-time data visualization and sorting capabilities",
    url: "https://res.cloudinary.com/dhvkeskni/image/upload/v1766331989/shorting-hat-login_mx49ff.png",
    languages: [
      "React",
      "JavaScript",
       'Redux', 
      "HTML5",
      "BootStrap",
      "Scss",
      "AmCharts",
    ],
    
    designStatus: "Dashboard",
  },

  {
    id: 2,
    projectName: "Flex MLOps",
    companyName: "@iot83",
    description:
      "Machine Learning Operations platform with flexible deployment options",
    image: "/flexv6login.png",
    languages: [
      "React",
      "TypeScript",
      'Redux', 
      "HTML5",
      "BootStrap",
      "Scss",
      "AmCharts",
    ],
    react: "React",
    html: "HTML5",
    framework: "BootStrap",
    scss: "Scss",
    amCharts: "AmCharts",
    designStatus: "Dashboard",
  },
  {
    id: 3,
    projectName: "Application Enablement platform - Version -5",
    companyName: "@iot83",
    description:
      "Comprehensive platform for rapid application development and deployment",
    url: "https://res.cloudinary.com/dhvkeskni/image/upload/v1766335231/Application_zm9aha.png",
    languages: [
      "React",
      "JavaScript",
      'Redux', 
      "HTML5",
      "BootStrap",
      "Scss",
      "AmCharts",
    ],
    
    designStatus: "Dashboard",
  },

  {
    id: 8,
    projectName: "Sales Portfolio",
    companyName: "@iot83",
    description: "Stakeholder and governance risk management system",
    image: "/sales-portfolio/sales-portfolio-login.png",
    languages: [
      "React",
      "JavaScript",
      'Redux', 
      "HTML5",
      "MUI",
      "Scss",
      "AmCharts",
    ],
    designStatus: "Dashboard",
  },
  {
    id: 9,
    projectName: "ARM-DLM-WEB",
    companyName: "@iot83",
    image: "/arm-dlm/dlm-login.png",
    description: "Stakeholder and governance risk management system",
    languages: [
      "React",
      "TypeScript",
      'Redux', 
      "MUI",
      "HTML5", 
      "Scss",
      "HighCharts",
      "Brightlayer UI",
    ],

    designStatus: "Dashboard",
  },
];
