export const socialIconData = [
  {
    id: 1,
    icon: "fab fa-instagram",
    name: "Instagram",
    className: "warning-outlined",
    sourceLink:
      "https://www.instagram.com/iftekharal7?igsh=MWZ5NTF1MXF0anVhcQ==",
  },
  {
    id: 2,
    icon: "fab fa-linkedin-in",
    name: "Linkedin",
    className: "primary-outlined",
    sourceLink: "https://www.linkedin.com/in/mohammad-iftekhar-8a3261194",
  },
  {
    id: 3,
    icon: "fab fa-github",
    name: "Github",
    className: "ghost-outlined",
    sourceLink: "https://github.com/iftekhar7",
  },
  {
    id: 4,
    icon: "fab fa-whatsapp",
    name: "WhatsApp",
    className: "primary-outlined",
    sourceLink: "https://wa.me/917626883755",
  },
  {
    id: 5,
    icon: "fas fa-envelope",
    name: "Email",
    className: "success-outlined",
    sourceLink: "mailto:iftekharhussain120@gmail.com",
  },
];

export const cardData = [
  {
    id: 6,
    projectName: "Shorting Hat",
    companyName: "@iot83",
     description: "Interactive dashboard with real-time data visualization and sorting capabilities",
    image: "/sorting-hat/shorting-hat-login.png",
    languages: [
      "React",
      "TypeScript",
      "HTML5",
      "BootStrap",
      "Scss",
      "AmCharts",
    ],
    react: "#React",
    html: "#HTML5",
    framework: "#BootStrap",
    scss: "#Scss",
    amCharts: "#AmCharts",
    designStatus: "Dashboard",
  },
  {
    id: 1,
    projectName: "Seimens",
    companyName: "@iot83",
    description: "Enterprise-level dashboard for industrial automation and monitoring",
    image: "/siemens/seimens1.png",
    languages: [
      "React",
      "TypeScript",
      "HTML5",
      "BootStrap",
      "Scss",
      "AmCharts",
    ],
    react: "#React",
    html: "#HTML5",
    framework: "#BootStrap",
    scss: "#Scss",
    amCharts: "#AmCharts",
    designStatus: "Dashboard",
  },
  {
    id: 2,
    projectName: "Flex MLOps",
    companyName: "@iot83",
     description: "Machine Learning Operations platform with flexible deployment options",
    image: "/flexv6login.png",
    languages: [
      "React",
      "TypeScript",
      "HTML5",
      "BootStrap",
      "Scss",
      "AmCharts",
    ],
    react: "#React",
    html: "#HTML5",
    framework: "#BootStrap",
    scss: "#Scss",
    amCharts: "#AmCharts",
    designStatus: "Dashboard",
  },
  {
    id: 3,
    projectName: "Application Enablement platform",
    companyName: "@iot83",
     description: "Comprehensive platform for rapid application development and deployment",
    image: "/Application.png",
    languages: [
      "React",
      "TypeScript",
      "HTML5",
      "BootStrap",
      "Scss",
      "AmCharts",
    ],
    react: "#React",
    html: "#HTML5",
    framework: "#BootStrap",
    scss: "#Scss",
    amCharts: "#AmCharts",
    designStatus: "Dashboard",
  },
  {
    id: 4,
    projectName: "OEDC",
    companyName: "@iot83",
    description: "Data studio application with MQTT integration and real-time analytics",
    image: "/oedc/oedc-login.png",
    languages: [
      "React",
      "TypeScript",
      "HTML5",
      "BootStrap",
      "Scss",
      "AmCharts",
    ],
    react: "#React",
    html: "#HTML5",
    framework: "#BootStrap",
    scss: "#Scss",
    amCharts: "#AmCharts",
    designStatus: "Dashboard",
  },
  {
    id: 5,
    projectName: "SGRM",
    companyName: "@iot83",
      description: "Stakeholder and governance risk management system",
    image: "/oedc/oedc-login.png",
    languages: [
      "React",
      "TypeScript",
      "HTML5",
      "BootStrap",
      "Scss",
      "AmCharts",
    ],
    react: "#React",
    html: "#HTML5",
    framework: "#BootStrap",
    scss: "#Scss",
    amCharts: "#AmCharts",
    designStatus: "Dashboard",
  },

  {
    id: 7,
    projectName: "Eaton DLM",
    companyName: "@iot83",
    image: "/eaton-dlm/dlm-login.png",
       description: "Stakeholder and governance risk management system",
    languages: [
      "React",
      "TypeScript",
      "HTML5",
      "#MUI",
      "Scss",
      "AmCharts",
    ],
    react: "#React",
    typeScript: "#TypeScrip",
    html: "#HTML5",
    framework: "#MUI",
    eatonLibrary: "#Brightlayer UI",
    scss: "#Scss",
    amCharts: "#AmCharts",
    designStatus: "Dashboard",
  },
  {
    id: 8,
    projectName: "Sales Portfolio",
    companyName: "@iot83",
       description: "Stakeholder and governance risk management system",
    image: "/sales-portfolio/sales-portfolio-login.png",
    languages: ["#React", "#JavaScript", "#HTML5", "#MUI", "#Scss", "#AmCharts"], 
    designStatus: "Dashboard",
  },
  {
    id: 9,
    projectName: "ARM-DLM-WEB",
    companyName: "@iot83",
    image: "/arm-dlm/dlm-login.png",
       description: "Stakeholder and governance risk management system",
    languages: [
      "#React",
      "#TypeScript",
      "#MUI",
      "#HTML5",
      ,
      "#Scss",
      "#HighCharts",
      "#Brightlayer UI",
    ],

    designStatus: "Dashboard",
  },
];
